/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 */

plugins {
    id("java-gradle-plugin")
    kotlin("jvm")
    `kotlin-dsl`
    `maven-publish`
}

group = "com.kneelawk"
val plugin_version: String by project
version = plugin_version

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven("https://maven.fabricmc.net/") { name = "Fabric" }
    maven("https://maven.architectury.dev/") { name = "Architectury" }
    maven("https://maven.quiltmc.org/repository/release") { name = "Quilt" }
    maven("https://maven.neoforged.net/releases/") { name = "NeoForged" }
    maven("https://kneelawk.com/maven") { name = "Kneelawk" }
}

dependencies {
    val loom_version: String by project
    compileOnly("net.fabricmc:fabric-loom:$loom_version")
}

gradlePlugin {
    plugins {
        create("remapCheckPlugin") {
            id = "com.kneelawk.remapcheck"
            implementationClass = "com.kneelawk.remapcheck.RemapCheckPlugin"
        }
    }
}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        val publishRepo = System.getenv("PUBLISH_REPO")
        if (publishRepo != null) {
            maven {
                name = "publishRepo"
                url = uri(rootProject.file(publishRepo))
            }
        }
    }
}
