# Performs all releases
name: release

on:
  push:
    tags:
      # matches things like v0.3.3
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
        env:
          RELEASE_TAG: ${{ github.ref_name }}
      - name: Capture Build Directory
        uses: actions/upload-artifact@v4
        with:
          name: build-dir
          path: build/
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelogs/changelog-${{ github.ref_name }}.md
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Maven Release
        run: ./gradlew publish -PkneelawkUsername=${{ secrets.MAVEN_USERNAME }} -PkneelawkPassword=${{ secrets.MAVEN_PASSWORD }}
        env:
          RELEASE_TAG: ${{ github.ref_name }}